### ISSUE TITLE
xilo saved excel files are not able to read with OLEDB

### ISSUE THREAD

**Issue by antoops** [codaxy/xlio#11]
I had already below code snippet for reading data from excel using OLEDB and I was trying to use xilo for writing data to excel.
```
  var fileName = string.Format("{0}\\FirstWorkbook.xlsx", Directory.GetCurrentDirectory());
            var connectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + fileName + ";Extended Properties=\"Excel 12.0\";";
            var adapter = new OleDbDataAdapter("SELECT * FROM [Sheet1$]", connectionString);
            var ds = new DataSet();
            adapter.Fill(ds, "Sheet1");
```

However when I try to read excel file which is saved by xilo, it is showing below error.

_An unhandled exception of type 'System.Data.OleDb.OleDbException' occurred in System.Data.dll Additional information: External table is not in the expected format._

Then I observed that file size change with xilo saving. i.e. i created an blank excel in my pc with Office 2013 which comes around 6KB and after using xilo sample code ([Firstworkbook.cs](https://github.com/codaxy/xlio/blob/master/Source/Codaxy.Xlio.Samples/Demos/FirstWorkbook.cs)), its size reduced to 3KB. 

As I am able to read other excel files with OLEDB code snippet, I guess the issue is with file formats of xilo saving. May I know the format or version xilo tries to write into excel?

**Comment by mstijak** [comment]
Xlio uses a subset of Open XML Schema. It might be that some elements are missing which are expected by the OleDbDataAdapter. 

It's very hard to say what exactly is causing the problem here. Our priority is that Xlio generated files work with Excel and Xlio itself.

I'm going to close this issue as I'm not sure what can be done here. Thanks for the report.
